import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { InputData, JSONSchemaInput, FetchingJSONSchemaStore, quicktype } from 'quicktype-core';
import { z } from 'zod';
import { wireSchemas } from '../src/index';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schemaDir = join(root, 'generated', 'json-schema');
const goFile = resolve(root, '../../apps/worker/internal/contracts/contracts.gen.go');

const sortKeys = (v: unknown): unknown => {
  if (Array.isArray(v)) return v.map(sortKeys);
  if (v && typeof v === 'object') {
    return Object.fromEntries(
      Object.entries(v as Record<string, unknown>)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, val]) => [k, sortKeys(val)]),
    );
  }
  return v;
};

/** Every registered schema keyed by its `meta({ id })`, with `$ref`s as `<Id>.json`. */
const registered = () =>
  (
    z.toJSONSchema(z.globalRegistry, {
      target: 'draft-2020-12',
      uri: (id) => `${id}.json`,
    }) as { schemas: Record<string, Record<string, unknown>> }
  ).schemas;

/** Bundle every schema under `$defs` so quicktype shares and keeps the names. */
const bundle = (all: Record<string, Record<string, unknown>>) => {
  const defs: Record<string, unknown> = {};
  for (const [id, s] of Object.entries(all)) {
    const rest = { ...s };
    delete rest.$schema;
    delete rest.$id;
    defs[id] = { title: id, ...rest };
  }
  const text = JSON.stringify({
    type: 'object',
    properties: Object.fromEntries(Object.keys(wireSchemas).map((n) => [n, { $ref: `${n}.json` }])),
    required: Object.keys(wireSchemas),
    additionalProperties: false,
    $defs: defs,
  }).replace(/"\$ref":"([A-Za-z]+)\.json"/g, '"$ref":"#/$defs/$1"');
  return JSON.parse(text) as unknown;
};

export async function generate(): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  const all = registered();
  for (const [id, schema] of Object.entries(all)) {
    out.set(join(schemaDir, `${id}.json`), JSON.stringify(sortKeys(schema), null, 2) + '\n');
  }
  const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
  await input.addSource({ name: 'Contracts', schema: JSON.stringify(bundle(all)) });
  const inputData = new InputData();
  inputData.addInput(input);
  const { lines } = await quicktype({
    inputData,
    lang: 'go',
    rendererOptions: { package: 'contracts', 'just-types': 'true' },
  });
  // The wrapper struct only exists to give quicktype one root; drop it.
  const body = lines
    .join('\n')
    .replace(/^package contracts\n*/m, '')
    .replace(/^type Contracts struct \{[^}]*\}\n*/m, '');
  // quicktype's constant casing is inconsistent (Ce, Mle, AC); use <Type><Value> everywhere.
  const named = body.replace(
    /^type (\w+) string\n\nconst \(\n([^)]*)\)/gm,
    (_m, type: string, consts: string) =>
      `type ${type} string\n\nconst (\n` +
      consts.replace(
        /^\t\w+(\s+)\w+ = "([^"]+)"/gm,
        (_c, sp: string, value: string) =>
          `\t${type}${value.replace(/[^A-Za-z0-9]/g, '').replace(/^./, (ch) => ch.toUpperCase())}${sp}${type} = "${value}"`,
      ) +
      ')',
  );
  const src =
    '// Code generated by pnpm contracts:gen. DO NOT EDIT.\n\npackage contracts\n\n' + named + '\n';
  const formatted = execFileSync('gofmt', [], { input: src }).toString();
  out.set(goFile, formatted);
  return out;
}

export async function check(): Promise<string[]> {
  const files = await generate();
  const stale: string[] = [];
  for (const [path, text] of files) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== text) stale.push(path);
  }
  if (existsSync(schemaDir)) {
    for (const f of readdirSync(schemaDir)) {
      if (!files.has(join(schemaDir, f))) stale.push(join(schemaDir, f));
    }
  }
  return stale;
}

async function main() {
  if (process.argv.includes('--check')) {
    const stale = await check();
    if (stale.length > 0) {
      console.error('Stale generated files:\n' + stale.map((s) => `  ${s}`).join('\n'));
      console.error('run pnpm contracts:gen');
      process.exit(1);
    }
    console.log('contracts: generated files are fresh');
    return;
  }
  const files = await generate();
  rmSync(schemaDir, { recursive: true, force: true });
  mkdirSync(schemaDir, { recursive: true });
  mkdirSync(dirname(goFile), { recursive: true });
  for (const [path, text] of files) writeFileSync(path, text);
  console.log(`contracts: wrote ${files.size} files`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
