// Code generated by pnpm contracts:gen. DO NOT EDIT.

package contracts

type JudgeJob struct {
	CustomInput        *string    `json:"customInput,omitempty"`
	EnqueuedAt         int64      `json:"enqueuedAt"`
	JobID              string     `json:"jobId"`
	Lane               Lane       `json:"lane"`
	Language           Language   `json:"language"`
	Mode               JobMode    `json:"mode"`
	Problem            ProblemRef `json:"problem"`
	RunVersion         int64      `json:"runVersion"`
	Seq                int64      `json:"seq"`
	Source             string     `json:"source"`
	StopOnFirstFailure bool       `json:"stopOnFirstFailure"`
	SubmissionID       string     `json:"submissionId"`
	Traceparent        string     `json:"traceparent"`
}

type ProblemRef struct {
	Checker     Checker `json:"checker"`
	Limits      Limits  `json:"limits"`
	TestsetHash string  `json:"testsetHash"`
	TestsetURI  string  `json:"testsetUri"`
	VersionID   string  `json:"versionId"`
}

type Checker struct {
	Eps       *float64    `json:"eps,omitempty"`
	Kind      CheckerKind `json:"kind"`
	SourceURI *string     `json:"sourceUri,omitempty"`
}

type Limits struct {
	MemMB    int64 `json:"memMb"`
	OutputKB int64 `json:"outputKb"`
	TimeMS   int64 `json:"timeMs"`
}

type JudgeProgress struct {
	Phase        JudgePhase   `json:"phase"`
	RunVersion   int64        `json:"runVersion"`
	SubmissionID string       `json:"submissionId"`
	Test         *TestOutcome `json:"test,omitempty"`
	Ts           int64        `json:"ts"`
	WorkerID     string       `json:"workerId"`
}

type TestOutcome struct {
	CheckerMsg *string `json:"checkerMsg,omitempty"`
	MemKB      int64   `json:"memKb"`
	No         int64   `json:"no"`
	Signal     *string `json:"signal,omitempty"`
	TimeMS     int64   `json:"timeMs"`
	Verdict    Verdict `json:"verdict"`
}

type JudgeResult struct {
	CompileLog   *string       `json:"compileLog,omitempty"`
	FinishedAt   int64         `json:"finishedAt"`
	MemKB        int64         `json:"memKb"`
	Output       *string       `json:"output,omitempty"`
	RunVersion   int64         `json:"runVersion"`
	Stderr       *string       `json:"stderr,omitempty"`
	SubmissionID string        `json:"submissionId"`
	Tests        []TestOutcome `json:"tests"`
	TimeMS       int64         `json:"timeMs"`
	Verdict      Verdict       `json:"verdict"`
	WorkerID     string        `json:"workerId"`
}

type Lane string

const (
	LaneContest     Lane = "contest"
	LaneInteractive Lane = "interactive"
	LanePractice    Lane = "practice"
	LaneRejudge     Lane = "rejudge"
)

type Language string

const (
	LanguageC       Language = "c"
	LanguageCpp17   Language = "cpp17"
	LanguageCpp20   Language = "cpp20"
	LanguageJava21  Language = "java21"
	LanguageNode    Language = "node"
	LanguagePython3 Language = "python3"
)

type JobMode string

const (
	JobModeRun      JobMode = "run"
	JobModeSubmit   JobMode = "submit"
	JobModeValidate JobMode = "validate"
)

type CheckerKind string

const (
	CheckerKindExact   CheckerKind = "exact"
	CheckerKindFloat   CheckerKind = "float"
	CheckerKindTestlib CheckerKind = "testlib"
	CheckerKindTokens  CheckerKind = "tokens"
)

type JudgePhase string

const (
	JudgePhaseClaimed   JudgePhase = "claimed"
	JudgePhaseCompiling JudgePhase = "compiling"
	JudgePhaseDone      JudgePhase = "done"
	JudgePhaseRunning   JudgePhase = "running"
)

type Verdict string

const (
	VerdictAC  Verdict = "AC"
	VerdictCE  Verdict = "CE"
	VerdictMLE Verdict = "MLE"
	VerdictOLE Verdict = "OLE"
	VerdictRE  Verdict = "RE"
	VerdictSE  Verdict = "SE"
	VerdictTLE Verdict = "TLE"
	VerdictWA  Verdict = "WA"
)
