/**
 * ED-01 (FR-EDIT-01): what the editors suggest beyond the words already typed. Monaco has no language service for
 * C, C++, Java or Python, so without this only `int` or `cout` that are already in the file ever appear. The lists are
 * what contestants actually type, not a whole standard library: a long list is noise.
 */
export type EntryKind = 'keyword' | 'function' | 'class' | 'snippet';

export interface Entry {
  label: string;
  kind: EntryKind;
  /** Inserted text. Snippets use Monaco's syntax (`${1:n}` tab stops, `$0` final cursor); omitted: the label. */
  insert?: string;
  detail?: string;
}

const kw = (...labels: string[]): Entry[] => labels.map((label) => ({ label, kind: 'keyword' }));
const fn = (...labels: string[]): Entry[] => labels.map((label) => ({ label, kind: 'function' }));
const cls = (...labels: string[]): Entry[] => labels.map((label) => ({ label, kind: 'class' }));
const sn = (label: string, detail: string, insert: string): Entry => ({
  label,
  kind: 'snippet',
  detail,
  insert,
});

const CPP_KEYWORDS = kw(
  'alignas',
  'auto',
  'bool',
  'break',
  'case',
  'catch',
  'char',
  'class',
  'const',
  'constexpr',
  'continue',
  'default',
  'delete',
  'do',
  'double',
  'else',
  'enum',
  'explicit',
  'false',
  'float',
  'for',
  'friend',
  'goto',
  'if',
  'inline',
  'int',
  'long',
  'mutable',
  'namespace',
  'new',
  'noexcept',
  'nullptr',
  'operator',
  'private',
  'protected',
  'public',
  'return',
  'short',
  'signed',
  'sizeof',
  'static',
  'struct',
  'switch',
  'template',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'typename',
  'union',
  'unsigned',
  'using',
  'virtual',
  'void',
  'while',
);

const CPP_LIBRARY: Entry[] = [
  ...cls(
    'vector',
    'string',
    'map',
    'unordered_map',
    'set',
    'unordered_set',
    'multiset',
    'multimap',
    'pair',
    'tuple',
    'array',
    'deque',
    'queue',
    'priority_queue',
    'stack',
    'bitset',
    'list',
    'string_view',
    'optional',
    'function',
    'greater',
    'less',
  ),
  ...fn(
    'sort',
    'stable_sort',
    'reverse',
    'lower_bound',
    'upper_bound',
    'binary_search',
    'max',
    'min',
    'swap',
    'abs',
    'gcd',
    'lcm',
    'accumulate',
    'iota',
    'fill',
    'memset',
    'next_permutation',
    'prev_permutation',
    'unique',
    'count',
    'find',
    'min_element',
    'max_element',
    'make_pair',
    'make_tuple',
    'to_string',
    'stoi',
    'stoll',
    'getline',
    'printf',
    'scanf',
    'cin',
    'cout',
    'cerr',
    'endl',
    'push_back',
    'emplace_back',
    'pop_back',
    'push',
    'pop',
    'top',
    'front',
    'back',
    'size',
    'empty',
    'clear',
    'begin',
    'end',
    'rbegin',
    'rend',
    'insert',
    'erase',
    'sqrt',
    'pow',
    'floor',
    'ceil',
    'INT_MAX',
    'INT_MIN',
    'LLONG_MAX',
    'LLONG_MIN',
    'ios::sync_with_stdio(false)',
    'cin.tie(nullptr)',
  ),
];

const CPP_SNIPPETS: Entry[] = [
  sn('for', 'for loop', 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}'),
  sn('forr', 'reverse for loop', 'for (int ${1:i} = ${2:n} - 1; ${1:i} >= 0; ${1:i}--) {\n\t$0\n}'),
  sn('fore', 'range-based for', 'for (auto& ${1:x} : ${2:v}) {\n\t$0\n}'),
  sn('while', 'while loop', 'while (${1:condition}) {\n\t$0\n}'),
  sn('if', 'if', 'if (${1:condition}) {\n\t$0\n}'),
  sn('ifelse', 'if / else', 'if (${1:condition}) {\n\t$2\n} else {\n\t$0\n}'),
  sn('switch', 'switch', 'switch (${1:x}) {\ncase ${2:0}:\n\t$0\n\tbreak;\ndefault:\n\tbreak;\n}'),
  sn('main', 'main function', 'int main() {\n\t$0\n\treturn 0;\n}'),
  sn('fastio', 'fast input and output', 'ios::sync_with_stdio(false);\ncin.tie(nullptr);\n'),
  sn(
    'tc',
    'read the number of test cases and loop',
    'int ${1:t};\ncin >> ${1:t};\nwhile (${1:t}--) {\n\t$0\n}',
  ),
  sn(
    'readvec',
    'read n numbers into a vector',
    'int ${1:n};\ncin >> ${1:n};\nvector<int> ${2:a}(${1:n});\nfor (auto& x : ${2:a}) cin >> x;\n',
  ),
  sn('vec', 'vector', 'vector<${1:int}> ${2:v}(${3:n});'),
  sn(
    'sortl',
    'sort with a lambda',
    'sort(${1:v}.begin(), ${1:v}.end(), [](const auto& a, const auto& b) {\n\treturn ${2:a < b};\n});',
  ),
  sn('lambda', 'lambda', '[&](${1:int x}) {\n\t$0\n}'),
  sn('struct', 'struct', 'struct ${1:Name} {\n\t$0\n};'),
  sn(
    'minheap',
    'min-heap',
    'priority_queue<${1:int}, vector<${1:int}>, greater<${1:int}>> ${2:pq};',
  ),
  sn('ll', 'long long alias', 'using ll = long long;'),
  sn('#include <bits/stdc++.h>', 'all of the standard library', '#include <bits/stdc++.h>'),
  sn('#include <iostream>', 'iostream', '#include <iostream>'),
  sn('#include <vector>', 'vector', '#include <vector>'),
  sn('#include <algorithm>', 'algorithm', '#include <algorithm>'),
];

const C_KEYWORDS = kw(
  'auto',
  'break',
  'case',
  'char',
  'const',
  'continue',
  'default',
  'do',
  'double',
  'else',
  'enum',
  'extern',
  'float',
  'for',
  'goto',
  'if',
  'int',
  'long',
  'register',
  'return',
  'short',
  'signed',
  'sizeof',
  'static',
  'struct',
  'switch',
  'typedef',
  'union',
  'unsigned',
  'void',
  'volatile',
  'while',
);

const C_LIBRARY: Entry[] = fn(
  'printf',
  'scanf',
  'puts',
  'getchar',
  'putchar',
  'fgets',
  'sprintf',
  'malloc',
  'calloc',
  'realloc',
  'free',
  'memset',
  'memcpy',
  'strlen',
  'strcmp',
  'strcpy',
  'strcat',
  'qsort',
  'abs',
  'sqrt',
  'pow',
  'atoi',
  'NULL',
  'INT_MAX',
  'INT_MIN',
  'LLONG_MAX',
  'size_t',
  'stdin',
  'stdout',
);

const C_SNIPPETS: Entry[] = [
  sn('for', 'for loop', 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}'),
  sn('while', 'while loop', 'while (${1:condition}) {\n\t$0\n}'),
  sn('if', 'if', 'if (${1:condition}) {\n\t$0\n}'),
  sn('ifelse', 'if / else', 'if (${1:condition}) {\n\t$2\n} else {\n\t$0\n}'),
  sn('main', 'main function', 'int main(void) {\n\t$0\n\treturn 0;\n}'),
  sn('readint', 'read an integer', 'int ${1:n};\nscanf("%d", &${1:n});\n'),
  sn(
    'readarr',
    'read n numbers into an array',
    'int ${1:n};\nscanf("%d", &${1:n});\nint ${2:a}[${1:n}];\nfor (int i = 0; i < ${1:n}; i++) scanf("%d", &${2:a}[i]);\n',
  ),
  sn(
    'cmp',
    'qsort comparator',
    'int ${1:cmp}(const void* a, const void* b) {\n\treturn *(const int*)a - *(const int*)b;\n}',
  ),
  sn('#include <stdio.h>', 'stdio', '#include <stdio.h>'),
  sn('#include <stdlib.h>', 'stdlib', '#include <stdlib.h>'),
  sn('#include <string.h>', 'string', '#include <string.h>'),
];

const JAVA_KEYWORDS = kw(
  'abstract',
  'boolean',
  'break',
  'byte',
  'case',
  'catch',
  'char',
  'class',
  'continue',
  'default',
  'do',
  'double',
  'else',
  'enum',
  'extends',
  'final',
  'finally',
  'float',
  'for',
  'if',
  'implements',
  'import',
  'instanceof',
  'int',
  'interface',
  'long',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'short',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'throws',
  'try',
  'var',
  'void',
  'while',
  'true',
  'false',
);

const JAVA_LIBRARY: Entry[] = [
  ...cls(
    'String',
    'StringBuilder',
    'Integer',
    'Long',
    'Double',
    'Character',
    'Math',
    'Arrays',
    'Collections',
    'List',
    'ArrayList',
    'LinkedList',
    'Map',
    'HashMap',
    'TreeMap',
    'Set',
    'HashSet',
    'TreeSet',
    'Deque',
    'ArrayDeque',
    'Queue',
    'PriorityQueue',
    'Stack',
    'Scanner',
    'BufferedReader',
    'InputStreamReader',
    'StringTokenizer',
    'PrintWriter',
    'BufferedWriter',
    'OutputStreamWriter',
    'IOException',
    'Comparator',
    'Optional',
    'Objects',
  ),
  ...fn(
    'System.out.println',
    'System.out.print',
    'System.out.printf',
    'System.in',
    'readLine',
    'nextInt',
    'nextLong',
    'nextToken',
    'hasNext',
    'hasMoreTokens',
    'parseInt',
    'parseLong',
    'length',
    'charAt',
    'substring',
    'toString',
    'toCharArray',
    'equals',
    'compareTo',
    'size',
    'isEmpty',
    'add',
    'get',
    'put',
    'containsKey',
    'getOrDefault',
    'sort',
    'fill',
    'max',
    'min',
    'abs',
    'sqrt',
    'pow',
    'MAX_VALUE',
    'MIN_VALUE',
  ),
];

const JAVA_SNIPPETS: Entry[] = [
  sn('for', 'for loop', 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}'),
  sn('fore', 'for-each', 'for (${1:int} ${2:x} : ${3:items}) {\n\t$0\n}'),
  sn('while', 'while loop', 'while (${1:condition}) {\n\t$0\n}'),
  sn('if', 'if', 'if (${1:condition}) {\n\t$0\n}'),
  sn('ifelse', 'if / else', 'if (${1:condition}) {\n\t$2\n} else {\n\t$0\n}'),
  sn('main', 'main method', 'public static void main(String[] args) throws IOException {\n\t$0\n}'),
  sn('sout', 'print a line', 'System.out.println(${1});'),
  sn(
    'reader',
    'fast line reader',
    'BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\nStringTokenizer st = new StringTokenizer(br.readLine());\nint ${1:n} = Integer.parseInt(st.nextToken());\n',
  ),
  sn(
    'writer',
    'buffered output',
    'PrintWriter out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(System.out)));\n$0\nout.flush();',
  ),
  sn(
    'scanner',
    'Scanner on stdin',
    'Scanner sc = new Scanner(System.in);\nint ${1:n} = sc.nextInt();\n',
  ),
  sn('list', 'ArrayList', 'List<${1:Integer}> ${2:list} = new ArrayList<>();'),
  sn('map', 'HashMap', 'Map<${1:Integer}, ${2:Integer}> ${3:map} = new HashMap<>();'),
  sn('sortl', 'sort with a comparator', 'Arrays.sort(${1:a}, (x, y) -> ${2:x - y});'),
  sn('import java.util.*;', 'java.util', 'import java.util.*;'),
  sn('import java.io.*;', 'java.io', 'import java.io.*;'),
];

const PY_KEYWORDS = kw(
  'False',
  'None',
  'True',
  'and',
  'as',
  'assert',
  'break',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'try',
  'while',
  'with',
  'yield',
);

const PY_LIBRARY: Entry[] = [
  ...fn(
    'print',
    'input',
    'len',
    'range',
    'sorted',
    'enumerate',
    'zip',
    'map',
    'filter',
    'sum',
    'min',
    'max',
    'abs',
    'reversed',
    'any',
    'all',
    'divmod',
    'pow',
    'round',
    'ord',
    'chr',
    'isinstance',
    'int',
    'str',
    'float',
    'list',
    'dict',
    'set',
    'tuple',
    'bool',
    'open',
    'append',
    'extend',
    'pop',
    'sort',
    'split',
    'strip',
    'join',
    'items',
    'keys',
    'values',
    'get',
    'add',
    'remove',
    'format',
    'heappush',
    'heappop',
    'heapify',
    'bisect_left',
    'bisect_right',
    'permutations',
    'combinations',
    'accumulate',
    'gcd',
    'sqrt',
    'lru_cache',
    'setrecursionlimit',
    'readline',
    'stdin',
    'stdout',
  ),
  ...cls('deque', 'Counter', 'defaultdict', 'OrderedDict', 'Fraction'),
];

const PY_SNIPPETS: Entry[] = [
  sn('for', 'for over a range', 'for ${1:i} in range(${2:n}):\n\t$0'),
  sn('fore', 'for over items', 'for ${1:x} in ${2:items}:\n\t$0'),
  sn('while', 'while loop', 'while ${1:condition}:\n\t$0'),
  sn('if', 'if', 'if ${1:condition}:\n\t$0'),
  sn('ifelse', 'if / else', 'if ${1:condition}:\n\t$2\nelse:\n\t$0'),
  sn('def', 'function', 'def ${1:name}(${2:args}):\n\t$0'),
  sn('class', 'class', 'class ${1:Name}:\n\tdef __init__(self${2}):\n\t\t$0'),
  sn('main', 'main guard', "if __name__ == '__main__':\n\t${1:main()}"),
  sn('fastinput', 'fast input', 'import sys\ninput = sys.stdin.readline\n'),
  sn('readints', 'read a line of integers', 'list(map(int, input().split()))'),
  sn(
    'readn',
    'read n then n integers',
    '${1:n} = int(input())\n${2:a} = list(map(int, input().split()))\n',
  ),
  sn('tc', 'loop over test cases', 'for _ in range(int(input())):\n\t$0'),
  sn('lambda', 'lambda', 'lambda ${1:x}: ${2:x}'),
  sn('listcomp', 'list comprehension', '[${1:x} for ${1:x} in ${2:items}]'),
  sn('import heapq', 'heapq', 'import heapq'),
  sn('import sys', 'sys', 'import sys'),
  sn('from collections import deque', 'deque', 'from collections import deque'),
  sn('from collections import defaultdict', 'defaultdict', 'from collections import defaultdict'),
];

const JS_KEYWORDS = kw(
  'async',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'else',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'let',
  'new',
  'null',
  'of',
  'return',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'undefined',
  'var',
  'while',
  'yield',
);

const JS_LIBRARY: Entry[] = [
  ...fn(
    'console.log',
    'require',
    'readFileSync',
    'split',
    'map',
    'filter',
    'reduce',
    'forEach',
    'join',
    'push',
    'pop',
    'shift',
    'slice',
    'splice',
    'sort',
    'indexOf',
    'includes',
    'parseInt',
    'Number',
    'String',
    'Math.max',
    'Math.min',
    'Math.floor',
    'Math.abs',
    'Math.sqrt',
    'JSON.parse',
    'JSON.stringify',
    'trim',
    'length',
  ),
  ...cls('Array', 'Map', 'Set', 'BigInt', 'Object', 'Math', 'JSON'),
];

const JS_SNIPPETS: Entry[] = [
  sn('for', 'for loop', 'for (let ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}'),
  sn('forof', 'for…of', 'for (const ${1:x} of ${2:items}) {\n\t$0\n}'),
  sn('while', 'while loop', 'while (${1:condition}) {\n\t$0\n}'),
  sn('if', 'if', 'if (${1:condition}) {\n\t$0\n}'),
  sn('ifelse', 'if / else', 'if (${1:condition}) {\n\t$2\n} else {\n\t$0\n}'),
  sn('function', 'function', 'function ${1:name}(${2:args}) {\n\t$0\n}'),
  sn('arrow', 'arrow function', 'const ${1:name} = (${2:args}) => {\n\t$0\n};'),
  sn(
    'readlines',
    'read all of stdin as lines',
    "const lines = require('fs').readFileSync(0, 'utf8').split('\\n');\n",
  ),
  sn('readnums', 'parse a line of numbers', 'const ${1:a} = lines[${2:0}].split(" ").map(Number);'),
  sn('log', 'console.log', 'console.log(${1});'),
];

/** A snippet named like a keyword (`for`, `while`) replaces it, so the list never shows the same word twice. */
const merge = (...lists: Entry[][]): Entry[] => {
  const all = lists.flat();
  const snippets = new Set(all.filter((e) => e.kind === 'snippet').map((e) => e.label));
  const seen = new Set<string>();
  return all.filter((e) => {
    if (e.kind === 'keyword' && snippets.has(e.label)) return false;
    if (seen.has(e.label)) return false;
    seen.add(e.label);
    return true;
  });
};

/** Keyed by Monaco language id (see `lib/languages.ts`). */
export const COMPLETIONS: Record<string, Entry[]> = {
  cpp: merge(CPP_KEYWORDS, CPP_LIBRARY, CPP_SNIPPETS),
  c: merge(C_KEYWORDS, C_LIBRARY, C_SNIPPETS),
  java: merge(JAVA_KEYWORDS, JAVA_LIBRARY, JAVA_SNIPPETS),
  python: merge(PY_KEYWORDS, PY_LIBRARY, PY_SNIPPETS),
  javascript: merge(JS_KEYWORDS, JS_LIBRARY, JS_SNIPPETS),
};

/** Where a line comment starts, so nothing is suggested inside one. */
export const LINE_COMMENT: Record<string, string> = {
  cpp: '//',
  c: '//',
  java: '//',
  python: '#',
  javascript: '//',
};
